version: '3.8'

services:
  amplify:
    build: ./web
    ports:
      # yarn dev
      - 3000:3000
      # mock api
      - 20002:20002
    stdin_open: true
    working_dir: '/app'
    volumes:
      - ../server:/app
      # credential,configを保管したい人向け
      # - ../dev/aws/:/root/.aws/
    tty: true